/*
  The MidWay API
  Copyright (C) 2000 Terje Eggestad

  The MidWay API is free software; you can redistribute it and/or
  modify it under the terms of the GNU Library General Public License as
  published by the Free Software Foundation; either version 2 of the
  License, or (at your option) any later version.
  
  The MidWay API is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Library General Public License for more details.
  
  You should have received a copy of the GNU Library General Public
  License along with the MidWay distribution; see the file COPYING. If not,
  write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330,
  Boston, MA 02111-1307, USA. 
*/

/*
 * $Id$
 * $Name$
 * 
 * $Log$
 * Revision 1.2  2000/07/20 19:38:37  eggestad
 * prototype fix up.
 *
 * Revision 1.1.1.1  2000/03/21 21:04:17  eggestad
 * Initial Release
 *
 * Revision 1.1.1.1  2000/01/16 23:20:12  terje
 * MidWay
 *
 */

#include <string.h>
#include <stdlib.h>

/* MAGIC are used to tag the ipcmain shm segment. */
#define MAGIC "MW10"

static char * RCSId = "$Id$";
static const char * Name = "$Name$";

/* RCS Name are to be on the format $Name$ , 
   where TYPE is either RELEASE, ALPHA, BETA, or EXPERIMENTAL (default).
   M, N, P are the version sumber, Major, minor, patchlevel.
*/

char * major = NULL, * minor = NULL, * patch = NULL;
const char * mwversion(void) 
{
  int len;
  /*  static char *  version = NULL; */
  static char version[1024];

  const char rcsname[] = { '$', 'N', 'a', 'm', 'e', '$', '\0' };
  const char rcsname2[] = "$Name$" ;
  char * buf, * t, * m, * n, * p;

  /*
  if (version != NULL) return version;
  */
  if (strcmp(Name , rcsname) == 0) 
    return "EXPERIMENTAL";

  if (strcmp(Name , rcsname2) == 0) 
    return "EXPERIMENTAL";

  buf = malloc(strlen(Name));
  strcpy(buf, Name);
  t = strchr(buf, ' ');
  t++;
  m = strchr(t, '_');
  *m = '\0';
  m++;

  n = strchr(m, '_');
  *n = '\0';
  n++;
  
  p = strchr(n, '_');
  *p = '\0';
  p++;
  
   /* THIS CAUSES malloc() to break !!!!!!!!!!!!!!!!!!! 
      eggis1 terje mwd 90> gdb ./mwd /home/terje/MidWay/terje/log/core
      GNU gdb 4.17.0.11 with Linux support
      Copyright 1998 Free Software Foundation, Inc.
      GDB is free software, covered by the GNU General Public License, and you are
      welcome to change it and/or distribute copies of it under certain conditions.
      Type "show copying" to see the conditions.
      There is absolutely no warranty for GDB.  Type "show warranty" for details.
      This GDB was configured as "i386-redhat-linux"...
      Core was generated by `./mwd -l debug'.
      Program terminated with signal 11, Segmentation fault.
      Reading symbols from /home/terje/projects/mw1/MidWay/src/lib/libMWipc.so...done.
      Reading symbols from /lib/libm.so.6...done.
      Reading symbols from /lib/libc.so.6...done.
      Reading symbols from /lib/ld-linux.so.2...done.
      Reading symbols from /lib/libnss_files.so.2...done.
      #0  0x4009d609 in chunk_free (ar_ptr=0x4012d580, p=0xe3e4e8f0) at malloc.c:3003
      malloc.c:3003: No such file or directory.
      (gdb) bt
      #0  0x4009d609 in chunk_free (ar_ptr=0x4012d580, p=0xe3e4e8f0) at malloc.c:3003
      #1  0x4009d38d in chunk_alloc (ar_ptr=0x4012d580, nb=1032) at malloc.c:2515
      #2  0x4009cb8a in __libc_malloc (bytes=1024) at malloc.c:2616
      #3  0x4001f424 in mwversion () at version.c:76
      #4  0x804a5ac in main (argc=3, argv=0xbffff874) at mwd.c:504
      #5  0x4005ccb3 in __libc_start_main (main=0x8049fcc <main>, argc=3, argv=0xbffff874, 
      init=0x8048f60 <_init>, fini=0x804d6ec <_fini>, rtld_fini=0x4000a350 <_dl_fini>, 
      stack_end=0xbffff86c) at ../sysdeps/generic/libc-start.c:78
      
      len = strlen(Name) + 100;
      version = malloc(len);
      version = malloc(1024);
   */  
  sprintf (version, "MidWay %s release version %s.%s.%s", t,m,n,p);
 
  major = m;
  minor = n;
  patch = p;   
  free (buf);
  buf = NULL;
  return version;
};
 
int _mwgetversion(int * vmaj, int * vmin, int * ptcl)
{
  if (major == NULL) {
    * vmaj = 0;
    * vmin = 0;
    * ptcl = 0;
  } else {
    * vmaj = atoi(major);
    * vmin = atoi(minor);
    * ptcl = atoi(patch);
  }
};

const char * _mwgetmagic(void)
{
  return MAGIC;
};
