#!/bin/sh

export CFLAGS='-g -DDEBUGGING -Wstrict-prototypes -Wmissing-declarations -Wimplicit -Wunused'
export CFLAGS='-g -DDEBUGGING -Wstrict-prototypes  -Wimplicit -Wunused'
#export CFLAGS='-g -DDEBUGGING -Wstrict-prototypes  -Wimplicit'
./configure
