.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (c) 1999 Terje Eggestad <terje.eggestad@iname.com>
.\" May be distributed under the GNU General Public License.
.\" $Id$
.\" $Name$
.\"
.TH MWADM 1 "DATE" Linux "MidWay Users Manual"
.SH NAME
mwadm \- The MidWay admin client
.SH SYNOPSIS
.B mwadm [-A url] [-l \fIdebuglevel\fP] [command args ...]
.SH DESCRIPTION
This is the terminal based manager client. It is still under 
heavy changes in use so the commands are not yet described here.
Use the online help in mwadm.

mwadm uses the readline library, so line editing and history
works, but completion only barely.

All commands are available non interactively thru the command line, just
place them after mwadm's options.

.SH ENVIRONMENT
.TP
.B MWURL
see 
.BR mwd (1). 
.TP
.B MWDIR
see 
.BR mwd (1). 
.SH SEE ALSO
.BR MidWay (7),  mwd (1), readline(3)

.SH WARNINGS

.SH BUGS

